In [207]:
import numpy as np
import pandas as pd

#### Size system components e.g. capacitor given the amount of energy needed to be stored. 

#### Find the maximum and minimum net energy available given different COD and storage capacitors.

In [208]:
# Energy harvested from single batch feed MFC, Joules (J) for different COD values

Emax = np.array([36.09,  # COD = 900
                 21.00,  # COD = 500
                 14.33,  # COD = 300
                 8.09    # COD = 70
                ])

Emax *= 0.5 # apply energy harvesting eff.
Emax

array([18.045, 10.5  ,  7.165,  4.045])

In [209]:
# max allowable voltage for comparator and voltage regulator, V for two configs : a & b
# a : comp:LTC1540, reg:LT3009
# b : comp:MAX9117, reg:TPS7A02

Vmax_a = 11
Vmax_b = 6

Vmin_a = 2
Vmin_b = 1.6

In [210]:
# Create a data frame for each system config

sys_a = pd.DataFrame(index=['cod_900', 'cod_500', 'cod_300', 'cod_70'])
sys_b = pd.DataFrame(index=['cod_900', 'cod_500', 'cod_300', 'cod_70'])

sys_a['Emax'] = Emax
sys_b['Emax'] = Emax

In [211]:
# capacitor needed to store Emax for each COD value at Vmax for each system config

sys_a.insert(0, 'C', sys_a.Emax / (0.5 * Vmax_a**2))
sys_b.insert(0, 'C', sys_b.Emax / (0.5 * Vmax_b**2))


# display(sys_a) 
# display(sys_b)

In [212]:
# Energy remaining at cut-off voltage of each system config
# (Energy at Vmin)

sys_a['Emin'] = 0.5 * sys_a.C * Vmin_a**2
sys_b['Emin'] = 0.5 * sys_b.C * Vmin_b**2

# display(sys_a) 
# display(sys_b)

In [213]:
# Minimum energy stored at lowest COD value tested (COD = 70)

sys_a['ECOD70'] = Emax[-1]
sys_b['ECOD70'] = Emax[-1]

# display(sys_a) 
# display(sys_b)

In [214]:
# # Max net energy available for use
sys_a['EaMax'] = sys_a.Emax - sys_a.Emin
sys_b['EaMax'] = sys_b.Emax - sys_b.Emin

# display(sys_a) 
# display(sys_b)

In [215]:
# # Max net energy available for use
sys_a['EaMin'] = sys_a.ECOD70 - sys_a.Emin
sys_b['EaMin'] = sys_b.ECOD70 - sys_b.Emin

# display(sys_a) 
# display(sys_b)

#### The amount of energy harvested determines how many samples can be taken by the data logger in the next batch. 

#### Use the energy consumption of each process to calculate the allowable number of samples corresponding to each COD value

In [216]:
Vop = 1.8 # + voltage pic microcontroller


# Energy consumed per event instance for each event type 

Eout = pd.DataFrame({'Current':  [1.18e-3, 2.85e-3, 2e-8], # A
                      'ExecTime':[0.1, 0.3, 7*24*60*60]}, # s
                     index=['sampling', 'estimation', 'sleep'])

Eout['Power'] = Eout.Current  * Vop # W

Eout['Energy'] = Eout.Power * Eout.ExecTime # J

Eout

            Current  ExecTime    Power    Energy
sampling    0.00118       0.1 0.002124 0.0002124
estimation  0.00285       0.3  0.00513  0.001539
sleep         2e-08 6.048e+05  3.6e-08  0.021773

In [217]:
def n_samples(Ea):
    return ( Ea - 
             Eout.Energy['estimation'] - 
             Eout.Energy['sleep'] -
             
           ) / Eout.Energy['sampling']

In [218]:
# # Max samples
sys_a['Nsamp_max'] = n_samples(sys_a.EaMax)
sys_b['Nsamp_max'] = n_samples(sys_b.EaMax)


# display(sys_a) 
# display(sys_b)

In [219]:
# Sampling time interval
sys_a['Nsamp_max_int'] = 7*24*60*60 / sys_a.Nsamp_max
sys_b['Nsamp_max_int'] = 7*24*60*60 / sys_b.Nsamp_max


# display(sys_a) 
# display(sys_b)

In [220]:
# Min samples
sys_a['Nsamp_min'] = n_samples(sys_a.EaMin)
sys_b['Nsamp_min'] = n_samples(sys_b.EaMin)


#display(sys_a) 
#display(sys_b)

In [221]:
# Sampling time interval
sys_a['Nsamp_min_int'] = 7*24*60*60 / sys_a.Nsamp_min
sys_b['Nsamp_min_int'] = 7*24*60*60 / sys_b.Nsamp_min


display(sys_a) 
display(sys_b)

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int
cod_900,0.29826,18.045,0.59653,4.045,17.448,3.4485,82039,7.3721,16126,37.505
cod_500,0.17355,10.5,0.34711,4.045,10.153,3.6979,47691,12.682,17300,34.959
cod_300,0.11843,7.165,0.23686,4.045,6.9281,3.8081,32509,18.604,17819,33.941
cod_70,0.06686,4.045,0.13372,4.045,3.9113,3.9113,18305,33.04,18305,33.04

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int
cod_900,1.0025,18.045,1.2832,4.045,16.762,2.7618,78806,7.6745,12893,46.909
cod_500,0.58333,10.5,0.74667,4.045,9.7533,3.2983,45810,13.202,15419,39.224
cod_300,0.39806,7.165,0.50951,4.045,6.6555,3.5355,31225,19.369,16536,36.575
cod_70,0.22472,4.045,0.28764,4.045,3.7574,3.7574,17580,34.402,17580,34.402

In [222]:
# Upper threshold voltage for comparator  
sys_a['Vth,h'] = np.sqrt( 2 * sys_a.ECOD70 / sys_a.C )
sys_b['Vth,h'] = np.sqrt( 2 * sys_b.ECOD70 / sys_b.C )

display(sys_a) 
display(sys_b)

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int,"Vth,h"
cod_900,0.29826,18.045,0.59653,4.045,17.448,3.4485,82039,7.3721,16126,37.505,5.208
cod_500,0.17355,10.5,0.34711,4.045,10.153,3.6979,47691,12.682,17300,34.959,6.8274
cod_300,0.11843,7.165,0.23686,4.045,6.9281,3.8081,32509,18.604,17819,33.941,8.265
cod_70,0.06686,4.045,0.13372,4.045,3.9113,3.9113,18305,33.04,18305,33.04,11

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int,"Vth,h"
cod_900,1.0025,18.045,1.2832,4.045,16.762,2.7618,78806,7.6745,12893,46.909,2.8407
cod_500,0.58333,10.5,0.74667,4.045,9.7533,3.2983,45810,13.202,15419,39.224,3.7241
cod_300,0.39806,7.165,0.50951,4.045,6.6555,3.5355,31225,19.369,16536,36.575,4.5082
cod_70,0.22472,4.045,0.28764,4.045,3.7574,3.7574,17580,34.402,17580,34.402,6