In [2]:
import numpy as np
import pandas as pd

#### Size system components e.g. capacitor given the amount of energy needed to be stored. 

#### Find the maximum and minimum net energy available given different COD and storage capacitors.

In [3]:
# Energy harvested from single batch feed MFC, Joules (J) for different COD values

Emax = np.array([36.09,  # COD = 900
                 21.00,  # COD = 500
                 14.33,  # COD = 300
                 8.09    # COD = 70
                ])

Emax *= 0.5 # apply energy harvesting eff.
Emax

array([18.045, 10.5  ,  7.165,  4.045])

In [4]:
# max allowable voltage for comparator and voltage regulator, V for two configs : a & b
# a : comp:LTC1540, reg:LT3009
# b : comp:MAX9117, reg:TPS7A02

Vmax_a = 11
Vmax_b = 6

Vmin_a = 2
Vmin_b = 1.6

In [5]:
# Create a data frame for each system config

sys_a = pd.DataFrame(index=['cod_900', 'cod_500', 'cod_300', 'cod_70'])
sys_b = pd.DataFrame(index=['cod_900', 'cod_500', 'cod_300', 'cod_70'])

sys_a['Emax'] = Emax
sys_b['Emax'] = Emax

In [6]:
# capacitor needed to store Emax for each COD value at Vmax for each system config

sys_a.insert(0, 'C', sys_a.Emax / (0.5 * Vmax_a**2))
sys_b.insert(0, 'C', sys_b.Emax / (0.5 * Vmax_b**2))


# display(sys_a) 
# display(sys_b)

In [7]:
# Energy remaining at cut-off voltage of each system config
# (Energy at Vmin)

sys_a['Emin'] = 0.5 * sys_a.C * Vmin_a**2
sys_b['Emin'] = 0.5 * sys_b.C * Vmin_b**2

# display(sys_a) 
# display(sys_b)

In [8]:
# Minimum energy stored at lowest COD value tested (COD = 70)

sys_a['ECOD70'] = Emax[-1]
sys_b['ECOD70'] = Emax[-1]

# display(sys_a) 
# display(sys_b)

In [9]:
# # Max net energy available for use
sys_a['EaMax'] = sys_a.Emax - sys_a.Emin
sys_b['EaMax'] = sys_b.Emax - sys_b.Emin

# display(sys_a) 
# display(sys_b)

In [10]:
# # Max net energy available for use
sys_a['EaMin'] = sys_a.ECOD70 - sys_a.Emin
sys_b['EaMin'] = sys_b.ECOD70 - sys_b.Emin

# display(sys_a) 
# display(sys_b)

#### The amount of energy harvested determines how many samples can be taken by the data logger in the next batch. 

#### Use the energy consumption of each process to calculate the allowable number of samples corresponding to each COD value

In [28]:
Vop = 1.8 # + voltage pic microcontroller


# Energy consumed per event instance for each event type 

Eout = pd.DataFrame({'Current':  [1.18e-3, 2.85e-3, 2e-8], # A
                      'ExecTime':[0.1, 0.3, 7*24*60*60]}, # s
                     index=['sampling', 'estimation', 'sleep'])

Eout

                 Current  ExecTime
sampling    1.180000e-03       0.1
estimation  2.850000e-03       0.3
sleep       2.000000e-08  604800.0

In [29]:
# energy consumed by system a
# a : comp:LTC1540, reg:LT3009
Eout_a = pd.DataFrame({'Current':  [0.3e-6, 3e-6], # A
                       'ExecTime': [7*24*60*60, 7*24*60*60]}, # s
                     index=        ['comparator', 'regulator'])


# energy consumed by system b
# b : comp:MAX9117, reg:TPS7A02
Eout_b = Eout_a
Eout_b.loc['comparator','Current'] = 0.6e-6
Eout_b.loc['regulator','Current'] = 25e-9

In [30]:
# Data frame for each system
Eout_a = Eout.append(Eout_a)
Eout_b = Eout.append(Eout_b)

In [31]:
Eout_a['Power'] = Eout_a.Current  * Vop # W
Eout_b['Power'] = Eout_b.Current  * Vop # W

Eout_a['Energy'] = Eout_a.Power * Eout_a.ExecTime # J
Eout_b['Energy'] = Eout_b.Power * Eout_b.ExecTime # J

In [32]:
Eout_a

                 Current  ExecTime         Power    Energy
sampling    1.180000e-03       0.1  2.124000e-03  0.000212
estimation  2.850000e-03       0.3  5.130000e-03  0.001539
sleep       2.000000e-08  604800.0  3.600000e-08  0.021773
comparator  6.000000e-07  604800.0  1.080000e-06  0.653184
regulator   2.500000e-08  604800.0  4.500000e-08  0.027216

In [34]:
def n_samples(Ea, Eout):
    return ( Ea - 
             Eout.Energy['estimation'] - 
             Eout.Energy['sleep'] -
             Eout.Energy['comparator'] -
             Eout.Energy['regulator']       
           ) / Eout.Energy['sampling']

In [35]:
# # Max samples
sys_a['Nsamp_max'] = n_samples(sys_a.EaMax, Eout_a)
sys_b['Nsamp_max'] = n_samples(sys_b.EaMax, Eout_b)


# display(sys_a) 
# display(sys_b)

In [36]:
# Sampling time interval
sys_a['Nsamp_max_int'] = 7*24*60*60 / sys_a.Nsamp_max
sys_b['Nsamp_max_int'] = 7*24*60*60 / sys_b.Nsamp_max


# display(sys_a) 
# display(sys_b)

In [39]:
# Min samples
sys_a['Nsamp_min'] = n_samples(sys_a.EaMin, Eout_a)
sys_b['Nsamp_min'] = n_samples(sys_b.EaMin, Eout_b)


#display(sys_a) 
#display(sys_b)

In [40]:
# Sampling time interval
sys_a['Nsamp_min_int'] = 7*24*60*60 / sys_a.Nsamp_min
sys_b['Nsamp_min_int'] = 7*24*60*60 / sys_b.Nsamp_min


display(sys_a) 
display(sys_b)

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int
cod_900,0.298264,18.045,0.596529,4.045,17.448471,3.448471,78835.966452,7.671625,12922.595454,46.801744
cod_500,0.173554,10.500,0.347107,4.045,10.152893,3.697893,44487.668371,13.594779,14096.896243,42.903061
cod_300,0.118430,7.165,0.236860,4.045,6.928140,3.808140,29305.219849,20.637962,14615.954312,41.379440
cod_70,0.066860,4.045,0.133719,4.045,3.911281,3.911281,15101.549867,40.048870,15101.549867,40.048870

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int
cod_900,1.002500,18.045,1.283200,4.045,16.761800,2.761800,75603.051789,7.999677,9689.680791,62.416917
cod_500,0.583333,10.500,0.746667,4.045,9.753333,3.298333,42606.504394,14.195016,12215.732266,49.509926
cod_300,0.398056,7.165,0.509511,4.045,6.655489,3.535489,28021.549383,21.583389,13332.283846,45.363571
cod_70,0.224722,4.045,0.287644,4.045,3.757356,3.757356,14376.853840,42.067618,14376.853840,42.067618

In [42]:
# Upper threshold voltage for comparator  
sys_a['Vth,h'] = np.sqrt( 2 * sys_a.ECOD70 / sys_a.C )
sys_b['Vth,h'] = np.sqrt( 2 * sys_b.ECOD70 / sys_b.C )

# display(sys_a) 
# display(sys_b)

In [45]:
# Lower threshold voltage for comparator  
sys_a['Vth,l'] = 2
sys_b['Vth,l'] = 1.6

print('System a')
display(sys_a) 
print('System b')
display(sys_b)

System a

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int,"Vth,h","Vth,l"
cod_900,0.298264,18.045,0.596529,4.045,17.448471,3.448471,78835.966452,7.671625,12922.595454,46.801744,5.208030,2
cod_500,0.173554,10.500,0.347107,4.045,10.152893,3.697893,44487.668371,13.594779,14096.896243,42.903061,6.827431,2
cod_300,0.118430,7.165,0.236860,4.045,6.928140,3.808140,29305.219849,20.637962,14615.954312,41.379440,8.265019,2
cod_70,0.066860,4.045,0.133719,4.045,3.911281,3.911281,15101.549867,40.048870,15101.549867,40.048870,11.000000,2

System b

,C,Emax,Emin,ECOD70,EaMax,EaMin,Nsamp_max,Nsamp_max_int,Nsamp_min,Nsamp_min_int,"Vth,h","Vth,l"
cod_900,1.002500,18.045,1.283200,4.045,16.761800,2.761800,75603.051789,7.999677,9689.680791,62.416917,2.840744,1.6
cod_500,0.583333,10.500,0.746667,4.045,9.753333,3.298333,42606.504394,14.195016,12215.732266,49.509926,3.724053,1.6
cod_300,0.398056,7.165,0.509511,4.045,6.655489,3.535489,28021.549383,21.583389,13332.283846,45.363571,4.508192,1.6
cod_70,0.224722,4.045,0.287644,4.045,3.757356,3.757356,14376.853840,42.067618,14376.853840,42.067618,6.000000,1.6